[build]
  command = "npm run build && npm run export"  # Menjalankan build dan export
  publish = "out"  # Menunjuk ke folder out yang dihasilkan oleh next export

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
