[build]
  command = "npm run build"  # Menjalankan build dan export
  publish = ".next"  # Menunjuk ke folder out yang dihasilkan oleh next export


[context.production.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
