[build]
  command = "npm run export"  # Ubah menjadi "npm run export"
  publish = "out"  # Tetap mengarah ke "out", karena itulah hasil dari "next export"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
