[build]
  command = "npm run build && npm run export"
  publish = "out"



[context.production.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
